Use 0.14 for now withouth statistics

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -71,38 +71,38 @@ jobs:
           recurse: true
           source: ValidationFiles/examples/*
 
-      - name: Collect results
-        id: collect-statistics
-        shell: python
-        run: |
-          import json, sys
-          success = True
-          github_report   = ""
-          def printStatistics(name, key):
-            global success, github_report, markdown_report
-            global steps_data
-            step_data = steps_data[key]
-            step_success = (step_data["outcome"] == "success")
-            success = success and step_success
-            with open(step_data["outputs"]["stats-file"], 'r') as sf:
-              stats = json.load(sf)
+      # - name: Collect results
+      #   id: collect-statistics
+      #   shell: python
+      #   run: |
+      #     import json, sys
+      #     success = True
+      #     github_report   = ""
+      #     def printStatistics(name, key):
+      #       global success, github_report, markdown_report
+      #       global steps_data
+      #       step_data = steps_data[key]
+      #       step_success = (step_data["outcome"] == "success")
+      #       success = success and step_success
+      #       with open(step_data["outputs"]["stats-file"], 'r') as sf:
+      #         stats = json.load(sf)
             
-              out_str = f'"{name}" {"succeeded" if step_success else "failed"} with {stats["fatal"]} fatal messages, {stats["error"]} errors, {stats["warning"]} warnings and {stats["information"]} information messages.'
-              if not step_success:
-                github_report   += f"::error::{out_str}%0A"
-              elif stats["warning"] > 0:
-                github_report   += f"::warning::{out_str}%0A"
-              else:
-                github_report   += f"\033[1;32mOk:\033[0m {out_str}%0A"
-          steps_data = json.loads("""${{ toJSON(steps) }}""")
-          printStatistics("Validate resources", "validate_CBBs")
-          print(f'::set-output name=result_status::{0 if success else 1}')
-          print(f'::set-output name=github_report::{github_report}')
+      #         out_str = f'"{name}" {"succeeded" if step_success else "failed"} with {stats["fatal"]} fatal messages, {stats["error"]} errors, {stats["warning"]} warnings and {stats["information"]} information messages.'
+      #         if not step_success:
+      #           github_report   += f"::error::{out_str}%0A"
+      #         elif stats["warning"] > 0:
+      #           github_report   += f"::warning::{out_str}%0A"
+      #         else:
+      #           github_report   += f"\033[1;32mOk:\033[0m {out_str}%0A"
+      #     steps_data = json.loads("""${{ toJSON(steps) }}""")
+      #     printStatistics("Validate resources", "validate_CBBs")
+      #     print(f'::set-output name=result_status::{0 if success else 1}')
+      #     print(f'::set-output name=github_report::{github_report}')
 
-      - name: Print results
-        run: |
-          echo "${{ steps.collect-statistics.outputs.github_report }}"
-          exit ${{ steps.collect-statistics.outputs.result_status }}
+      # - name: Print results
+      #   run: |
+      #     echo "${{ steps.collect-statistics.outputs.github_report }}"
+      #     exit ${{ steps.collect-statistics.outputs.result_status }}
 
 
 
