Split jobs and add new FHIR validation action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,11 +36,6 @@ jobs:
         with:
           dotnet-version: 3.1.x
       
-      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
-      - name: Setup Java JDK
-        uses: actions/setup-java@v1.4.3
-        with:
-          java-version: 1.8
         
 #      - name: Firely.Terminal validation
 #        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
@@ -51,24 +46,95 @@ jobs:
 #          OUTPUT_FORMAT: SUMMARY
 #          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
 #          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
+     
+
+  JAVA_FHIR_VALIDATION:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+      # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Gather files to validate
         run: |
            chmod +x ./.github/scripts/GetValidationFiles.sh
            .github/scripts/GetValidationFiles.sh
 
-      - name: Java validation of resources and terminology
-        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
+      - name: Run the validator against the CBBs
+        id: validate_CBBs
+        uses: pieter-edelman-nictiz/hl7-validator-action@master
         with:
-          PATH_TO_CONFORMANCE_RESOURCES: ValidationFiles/resources ValidationFiles/terminology
-          PATH_TO_EXAMPLES: ValidationFiles/examples
-          PATH_TO_QUALITY_CONTROL_RULES: qa-validate-all
-          DOTNET_VALIDATION_ENABLED: FALSE
-          JAVA_VALIDATION_ENABLED: TRUE
-          #JAVA_VALIDATION_OPTIONS: -html-output ./validation-output-resources.html
-          OUTPUT_FORMAT: RAW
-          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
-          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
+          version: "4.0"
+          ig: ValidationFiles/resources/ ValidationFiles/terminology
+          recurse: true
+          source: ValidationFiles/examples/*
+
+      - name: Collect results
+        id: collect-statistics
+        shell: python
+        run: |
+          import json, sys
+          success = True
+          github_report   = ""
+          def printStatistics(name, key):
+            global success, github_report, markdown_report
+            global steps_data
+            step_data = steps_data[key]
+            if step_data["outputs"]["was-skipped"] == 'true':
+              out_str = f'Test "{name}" was skipped'
+              return
+            step_success = (step_data["outcome"] == "success")
+            success = success and step_success
+            with open(step_data["outputs"]["stats-file"], 'r') as sf:
+              stats = json.load(sf)
+              
+              if "fatal" not in stats:
+                out_str = f'"{name}" failed to run.'
+                github_report   += f"::error::{out_str}%0A"
+              else:
+                out_str = f'"{name}" {"succeeded" if step_success else "failed"} with {stats["fatal"]} fatal messages, {stats["error"]} errors, {stats["warning"]} warnings and {stats["information"]} information messages.'
+                if not step_success:
+                  github_report   += f"::error::{out_str}%0A"
+                elif stats["warning"] > 0:
+                  github_report   += f"::warning::{out_str}%0A"
+                else:
+                  github_report   += f"\033[1;32mOk:\033[0m {out_str}%0A"
+          steps_data = json.loads("""${{ toJSON(steps) }}""")
+          printStatistics("Validate CBB resources", "validate_CBBs")
+          print(f'::set-output name=result_status::{0 if success else 1}')
+          print(f'::set-output name=github_report::{github_report}')
+
+      - name: Print results
+        run: |
+          echo "${{ steps.collect-statistics.outputs.github_report }}"
+          exit ${{ steps.collect-statistics.outputs.result_status }}
+
+
+
+
+
+      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
+#      - name: Setup Java JDK
+#        uses: actions/setup-java@v1.4.3
+#        with:
+#          java-version: 1.8
+#
+#
+#
+#      - name: Java validation of resources and terminology
+#        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
+#        with:
+#          PATH_TO_CONFORMANCE_RESOURCES: ValidationFiles/resources ValidationFiles/terminology
+#          PATH_TO_EXAMPLES: ValidationFiles/examples
+#          PATH_TO_QUALITY_CONTROL_RULES: qa-validate-all
+#          DOTNET_VALIDATION_ENABLED: FALSE
+#          JAVA_VALIDATION_ENABLED: TRUE
+#          #JAVA_VALIDATION_OPTIONS: -html-output ./validation-output-resources.html
+#          OUTPUT_FORMAT: RAW
+#          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
+#          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
 
 #      - name: Java validation of examples
 #        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
@@ -87,4 +153,4 @@ jobs:
 #        uses: actions/upload-artifact@v3
 #        with:
 #          name: FHIR-validation-results
-#          path: ./validation-output-resources.html         
+#          path: ./validation-output-resources.html 
